name: 'Publish TestFlight'
description: 'Publish TestFlight GitHub action'
inputs:
  api-key:
    description: 'The App Connect API Key'
    required: false
  api-key-path:
    description: 'The App Connect API Key path'
    required: false
  ipa-path:
    description: 'IPA file path to upload'
    required: true
  issuer-id:
    description: 'Issuer ID'
    required: true
  key-id:
    description: 'Key ID'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "upload-cloud"
  color: "orange"