name: 'Publish TestFlight'
description: 'Publish TestFlight GitHub action'
inputs:
  api-key:
    description: >
      App Connect API Key
    required: false
  api-key-path:
    description: >
      Path of the file that converted the API key to JSON format
    required: false
  ipa-path:
    description: 'IPA file path to upload'
    required: false
  issuer-id:
    description: 'Issuer ID'
    required: false
  key-id:
    description: 'Key ID'
    required: false
  output-directory:
    description: >
      Specifies the output directory for JSON files.
      If omitted, `runner.temp` is set.
    required: false
    default: ${{ runner.temp }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "upload-cloud"
  color: "orange"